[package]
name = "yadaw-dsp-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
yadaw-dsp-core.workspace = true
yadaw-dsp-runtime.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "render_runtime"
harness = false

[lints]
workspace = true
