[package]
name = "yadaw-audio-host-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ipc-channel.workspace = true
napi.workspace = true
napi-derive.workspace = true
rmp-serde.workspace = true
yadaw-dsp-runtime.workspace = true
yadaw-ipc-transport.workspace = true

[build-dependencies]
napi-build.workspace = true

[lints]
workspace = true
