/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AudioHostIpcClient {
  constructor(executablePath: string, bridgePath: string, crashMarkerPath: string)
  request(messagePackRequest: Buffer): Promise<Buffer>
  close(): void
}
