/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AudioHostIpcClient {
  constructor(executablePath: string, crashMarkerPath: string, workerThreads?: number | undefined | null, maxBlockingThreads?: number | undefined | null, egressConcurrency?: number | undefined | null)
  request(messagePackRequest: Buffer, attachments?: Array<Buffer> | undefined | null): Promise<IpcResponse>
  heartbeat(messagePackRequest: Buffer): Promise<IpcResponse>
  readTelemetry(): Buffer
  enqueueParameter(targetKind: string, runtimeHandle: number, parameterId: number, normalized: number, gesture: string): string
  transportDiagnostics(): Buffer
  get sessionEpoch(): number
  drainEvents(): Array<Buffer>
  close(): void
}

export interface IpcResponse {
  body: Buffer
  attachments: Array<Buffer>
}
