/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AudioHostIpcClient {
  constructor(executablePath: string, crashMarkerPath: string, workerThreads?: number | undefined | null, maxBlockingThreads?: number | undefined | null, egressConcurrency?: number | undefined | null, editorOwnerWindowHandle?: Buffer | undefined | null)
  request(messagePackRequest: Buffer, attachments?: Array<Buffer> | undefined | null): Promise<IpcResponse>
  heartbeat(messagePackRequest: Buffer): Promise<IpcResponse>
  readTelemetry(): Buffer
  enqueueParameter(request: ParameterEnqueueRequest): ParameterEnqueueResult
  transportDiagnostics(): Buffer
  get sessionEpoch(): number
  get helperEpoch(): string
  get persistentSharedPages(): boolean
  drainEvents(): Array<Buffer>
  close(): void
}

export interface IpcResponse {
  body: Buffer
  attachments: Array<Buffer>
}

export interface ParameterEnqueueRequest {
  targetKind: string
  runtimeHandle: number
  parameterId: number
  normalized: number
  gesture: string
  sequence?: string
  targetGeneration?: number
}

export interface ParameterEnqueueResult {
  outcome: string
  sequence: string
}
