[package]
name = "yadaw-shared-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
serde = ["dep:serde"]

[dependencies]
getrandom.workspace = true
serde = { workspace = true, optional = true }
thiserror.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Memory",
] }

[lints]
workspace = true
