[package]
name = "yadaw-audio-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bwavfile.workspace = true
futures-util.workspace = true
ipc-channel.workspace = true
libloading.workspace = true
ringbuf.workspace = true
rmp-serde.workspace = true
tokio.workspace = true
winit.workspace = true
yadaw-dsp-core.workspace = true
yadaw-dsp-runtime.workspace = true
yadaw-ipc-transport.workspace = true
yadaw-vst3-host.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
cpal = { workspace = true, features = ["asio"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
cpal.workspace = true

[lints]
workspace = true

[features]
default = []
bench-internals = []
