[package]
name = "yadaw-audio-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
libloading.workspace = true
yadaw-dsp-core.workspace = true
yadaw-dsp-runtime.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
cpal = { workspace = true, features = ["asio"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
cpal.workspace = true

[lints.rust]
unsafe_code = "allow"
