[package]
name = "yadaw-dsp-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
asio = ["cpal/asio"]
bench-internals = []

[dependencies]
bwavfile.workspace = true
cpal.workspace = true
napi.workspace = true
napi-derive.workspace = true
ringbuf.workspace = true
rubato.workspace = true
sha2.workspace = true
yadaw-dsp-core.workspace = true

[build-dependencies]
napi-build.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "native_render"
harness = false
required-features = ["bench-internals"]

[[bench]]
name = "media_streaming"
harness = false
required-features = ["bench-internals"]

[[bench]]
name = "recording"
harness = false
required-features = ["bench-internals"]
