/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzeWaveform(path: string): Promise<NativeAnalyzedWaveform>

export declare function engineInfo(): NativeEngineInfo

export declare function finalizeRecording(config: NativeFinalizeRecordingConfig): Promise<NativeFinalizedRecording>

export interface NativeAnalyzedWaveform {
  sampleRate: number
  channels: number
  frameCount: number
  waveformLevels: Array<NativeWaveformLevel>
}

export interface NativeAudioBenchmarkReport {
  durationMs: number
  overallRealtimeFactor: number
  scenarios: Array<NativeAudioBenchmarkScenario>
}

export interface NativeAudioBenchmarkScenario {
  id: string
  label: string
  description: string
  sampleRate: number
  blockSize: number
  tracks: number
  buses: number
  sends: number
  elapsedMs: number
  audioDurationMs: number
  averageBlockMs: number
  bufferBudgetMs: number
  realtimeFactor: number
}

export interface NativeEngineInfo {
  backend: string
  version: string
  nodeApi: number
}

export interface NativeFinalizedRecording {
  path: string
  contentHash: string
  sampleRate: number
  channels: number
  bitDepth: string
  frameCount: number
  timeReference: number
  waveformLevels: Array<NativeWaveformLevel>
}

export interface NativeFinalizeRecordingConfig {
  inputPath: string
  outputPath: string
  targetSampleRate: number
  bitDepth: string
  assetId: string
  originator: string
  originationDate: string
  originationTime: string
  timeReference: number
  channelIndices?: Array<number>
}

export interface NativeMidiEvent {
  tick: number
  channel?: number
  kind: string
  data: Buffer
}

export interface NativeMidiNote {
  startTick: number
  durationTicks: number
  channel: number
  key: number
  velocity: number
  releaseVelocity: number
}

export interface NativeMidiTrack {
  sourceTrack: number
  sequence: number
  name: string
  lengthTicks: number
  notes: Array<NativeMidiNote>
  events: Array<NativeMidiEvent>
  tempoEvents: Array<NativeTempoEvent>
  timeSignatureEvents: Array<NativeTimeSignatureEvent>
  warnings: Array<string>
}

export interface NativeNormalizedSmf {
  format: number
  sourceTiming: string
  tracks: Array<NativeMidiTrack>
  tempoEvents: Array<NativeTempoEvent>
  timeSignatureEvents: Array<NativeTimeSignatureEvent>
  warnings: Array<string>
}

export interface NativeRecordingResult {
  path: string
  sampleRate: number
  channels: number
  frameCount: number
  dropoutFrames: number
}

export interface NativeRecordingStartConfig {
  path: string
  assetId: string
  originator: string
  originationDate: string
  originationTime: string
  timeReference: number
}

export interface NativeTempoEvent {
  tick: number
  beatsPerMinute: number
}

export interface NativeTempoMap {
  tempoEvents: Array<NativeTempoEvent>
  timeSignatureEvents: Array<NativeTimeSignatureEvent>
}

export interface NativeTimeSignatureEvent {
  tick: number
  numerator: number
  denominator: number
}

export interface NativeWaveformLevel {
  framesPerBucket: number
  bucketCount: number
  peaks: Buffer
}

export declare function parseMidiFile(path: string, projectTempoMap: NativeTempoMap): Promise<NativeNormalizedSmf>

export declare function processGain(samples: Array<number>, gain: number): ProcessGainResult

export interface ProcessGainResult {
  samples: Array<number>
  peak: number
}

export declare function repairRecordingHeader(path: string, channels: number): number

export declare function runAudioBenchmark(): Promise<NativeAudioBenchmarkReport>

export declare function writeDeterministicTestRecording(config: NativeRecordingStartConfig, sampleRate: number, frameCount: number): NativeRecordingResult
