/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzeWaveform(path: string): Promise<NativeAnalyzedWaveform>

export declare function audioEngineSnapshot(): NativeAudioRuntimeSnapshot

export declare function engineInfo(): NativeEngineInfo

export declare function finalizeRecording(config: NativeFinalizeRecordingConfig): Promise<NativeFinalizedRecording>

export declare function listAudioBackends(): Array<NativeAudioBackend>

export declare function listAudioDevices(backend: string): NativeAudioDeviceList

export interface NativeAnalyzedWaveform {
  sampleRate: number
  channels: number
  frameCount: number
  waveformLevels: Array<NativeWaveformLevel>
}

export interface NativeAudioBackend {
  id: string
  label: string
  available: boolean
}

export interface NativeAudioDevice {
  id: string
  name: string
  isDefault: boolean
  defaultSampleRate?: number
  minBufferSize?: number
  maxBufferSize?: number
}

export interface NativeAudioDeviceList {
  inputs: Array<NativeAudioDevice>
  outputs: Array<NativeAudioDevice>
}

export interface NativeAudioEngineConfig {
  backend: string
  inputDeviceId: string
  outputDeviceId: string
  bufferSize: number
}

export interface NativeAudioRuntimeSnapshot {
  state: string
  requestedBufferSize?: number
  sampleRate?: number
  inputSampleRate?: number
  inputBufferSize?: number
  outputBufferSize?: number
  ringBufferCapacityFrames?: number
  ringBufferFillFrames?: number
  inputLatencyMs?: number
  outputLatencyMs?: number
  ringBufferLatencyMs?: number
  engineLatencyMs?: number
  estimatedRoundTripLatencyMs?: number
  xruns: number
  clockSync: string
  bufferFallback: boolean
}

export interface NativeEngineInfo {
  backend: string
  version: string
  nodeApi: number
}

export interface NativeFinalizedRecording {
  path: string
  contentHash: string
  sampleRate: number
  channels: number
  bitDepth: string
  frameCount: number
  timeReference: number
  waveformLevels: Array<NativeWaveformLevel>
}

export interface NativeFinalizeRecordingConfig {
  inputPath: string
  outputPath: string
  targetSampleRate: number
  bitDepth: string
  assetId: string
  originator: string
  originationDate: string
  originationTime: string
  timeReference: number
}

export interface NativeRecordingResult {
  path: string
  sampleRate: number
  channels: number
  frameCount: number
  dropoutFrames: number
}

export interface NativeRecordingStartConfig {
  path: string
  assetId: string
  originator: string
  originationDate: string
  originationTime: string
  timeReference: number
}

export interface NativeWaveformLevel {
  framesPerBucket: number
  bucketCount: number
  peaks: Buffer
}

export interface NativeWaveformSnapshot {
  sampleRate: number
  channels: number
  frameCount: number
  startFrame: number
  endFrame: number
  framesPerBucket: number
  bucketCount: number
  peaks: Buffer
}

export declare function processGain(samples: Array<number>, gain: number): ProcessGainResult

export interface ProcessGainResult {
  samples: Array<number>
  peak: number
}

export declare function recordingWaveformSnapshot(startFrame: number, endFrame: number, maxBuckets: number): NativeWaveformSnapshot

export declare function repairRecordingHeader(path: string, channels: number): number

export declare function startAudioEngine(config: NativeAudioEngineConfig): NativeAudioRuntimeSnapshot

export declare function startRecording(config: NativeRecordingStartConfig): void

export declare function stopAudioEngine(): NativeAudioRuntimeSnapshot

export declare function stopRecording(): NativeRecordingResult

export declare function writeDeterministicTestRecording(config: NativeRecordingStartConfig, sampleRate: number, frameCount: number): NativeRecordingResult
