[package]
name = "yadaw-ipc-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ipc-channel.workspace = true
rmp-serde.workspace = true
serde.workspace = true
thiserror.workspace = true
xxhash-rust.workspace = true
yadaw-dsp-runtime.workspace = true

[dev-dependencies]
loom = "0.7.2"

[lints.rust]
unsafe_code = "allow"
